"""Petz

Revision ID: 3ad38b890c74
Revises: a42c8bf08e45
Create Date: 2023-04-21 10:20:20.229779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad38b890c74'
down_revision = 'a42c8bf08e45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pets',
    sa.Column('PetId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=4096), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('PetId')
    )
    op.create_index(op.f('ix_Pets_Name'), 'Pets', ['Name'], unique=False)
    op.create_index(op.f('ix_Pets_PetId'), 'Pets', ['PetId'], unique=False)
    op.create_index(op.f('ix_Pets_user_id'), 'Pets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Pets_user_id'), table_name='Pets')
    op.drop_index(op.f('ix_Pets_PetId'), table_name='Pets')
    op.drop_index(op.f('ix_Pets_Name'), table_name='Pets')
    op.drop_table('Pets')
    # ### end Alembic commands ###
