"""updated address

Revision ID: a42c8bf08e45
Revises: 9f3ee5fde992
Create Date: 2023-03-09 15:06:28.312231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42c8bf08e45'
down_revision = '9f3ee5fde992'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address_line1', sa.String(length=128), nullable=False))
    op.add_column('address', sa.Column('address_line2', sa.String(length=128), nullable=False))
    op.drop_column('address', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('address', 'address_line2')
    op.drop_column('address', 'address_line1')
    # ### end Alembic commands ###
